app-template:
  serviceAccount:
    name: tailscale
  controllers:
    tailscale:
      containers:
        app:
          image:
            repository: ghcr.io/tailscale/tailscale
            tag: latest
          env:
            TS_HOSTNAME: homelab-router
            TS_USERSPACE: false
            TS_KUBE_SECRET: tailscale
